FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip ca-certificates \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir "mineru[pipeline,vlm]==2.7.6"

WORKDIR /workspace
